name: Daily Update

on:
  schedule:
    - cron: "0 10 * * *" # Runs at 10:00 AM UTC daily

  workflow_dispatch: # Allow manual triggers

jobs:
  daily-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add timestamp to a file
        run: |
          echo "Last updated: $(date)" > last_updated.txt

      - name: Commit changes (24f2007378@ds.study.iitm.ac.in)
        run: |
          git config --local user.email "24f2007378@ds.study.iitm.ac.in"
          git config --local user.name "github-actions[bot]"
          git add last_updated.txt
          git commit -m "Daily update [skip ci]" || exit 0 # exit 0 handles no changes

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
