name: Daily Commit Workflow

on:
  schedule:
    # Cron syntax to run the workflow daily at 2:00 AM UTC
    - cron: '0 2 * * *'  

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add daily commit by 24f2007378@ds.study.iitm.ac.in
      run: |
        # Create a new file or modify an existing one
        echo "Daily commit at $(date)" > daily_commit_log.txt
        
        # Stage the changes
        git add daily_commit_log.txt
        
        # Commit the changes
        git config --global user.email "24f2007378@ds.study.iitm.ac.in"
        git config --global user.name "DevSync Automation"
        git commit -m "Automated daily commit by 24f2007378@ds.study.iitm.ac.in"
        
        # Push the commit to the repository
        git push

    - name: Confirm commit and push
      run: |
        # Show the latest commit for verification
        git log -n 1
